#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -U compinit
compinit
zstyle ':completion:*:default' menu select=2

# alias
alias ls='ls -G'
alias ll='ls -la'

alias tn='tmux'
alias tls='tmux ls'
alias ta='tmux a'

alias gf='git-foresta --all --style=10 | less -RSX'

alias pgstart='pg_ctl -l /usr/local/var/postgres/server.log start'
alias pgstop='pg_ctl stop'
