typeset -gU cdpath fpath mailpath path
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.bin:$PATH
export PATH=~/go/bin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.zsh/completions:$PATH"
